---
# task api_export

- name: use eonapi to export configuration
  uri:
    url: "{{api_url}}/exportConfiguration?username={{api_user}}&apiKey={{api_token}}"
    method: POST
    headers:
      Content-Type: "application/json"
    body: '{ "jobName" : "{{ jobName }}" }'
    body_format: json
    return_content: yes
    validate_certs: no
  register: return

- name : display result
  debug:
    msg: "{{ return.content }}"
    
- name: Fail if ERROR in the page content
  fail:
  when: "'ERROR' in return.content"