---
# task api_add_host

- name: use eonapi to create host
  uri:
    url: "{{api_url}}/createHost?username={{api_user}}&apiKey={{api_token}}"
    method: POST
    return_content: yes
    validate_certs: no
    HEADER_Content-Type: "application/json"
    body: '{ "hostName" : "{{ hostName }}", "hostIp" : "{{ hostIp }}", "hostAlias" : "{{ hostAlias }}" }'
  register: return

- name : display result
  debug:
    msg: return.content

- name: Fail if 200 OK is not in the page content
  fail:
  when: "'200 OK' not in return.content"