---
- name: remove conflicting grafana packages
  package:
    name: grafana-data
    state: absent
  register: _old_grafana_pkgs

- name: add grafana repository
  yum_repository:
    name: grafana
    description: grafana
    baseurl: "{{ grafana_repo }}"
    gpgcheck: yes
    gpgkey: "{{ grafana_repo_key }}"

- name: install grafana
  package:
    name: "{{ grafana_package }}"
    state: "{{ (grafana_version == 'latest') | ternary('latest', 'present') }}"
  register: _install_packages
  until: _install_packages is succeeded
  retries: 5
  delay: 2
  notify: restart grafana

- name: start and enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
  when: grafana_firewalld

- name: open port 3000
  firewalld:
    port: 3000/tcp
    permanent: true
    immediate: true
    state: enabled
  when: grafana_firewalld