---
- name: grafana - remove conflicting packages
  package:
    name: grafana-data
    state: absent
  register: _old_grafana_pkgs

- name: grafana - add repository
  yum_repository:
    name: grafana
    description: grafana
    baseurl: "{{ grafana_repo }}"
    gpgcheck: yes
    gpgkey: "{{ grafana_repo_key }}"

- name: grafana - install packages
  package:
    name: "{{ grafana_package }}"
    state: "{{ (grafana_version == 'latest') | ternary('latest', 'present') }}"
  register: _install_packages
  until: _install_packages is succeeded
  retries: 5
  delay: 2

- name: grafana - enable service
  systemd:
    name: grafana-server
    state: started
    enabled: yes
    daemon_reload: yes
      
- name: grafana - start and enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
  when: grafana_firewalld

- name: grafana - open port 3000
  firewalld:
    port: 3000/tcp
    permanent: true
    immediate: true
    state: enabled
  when: grafana_firewalld