---
- name: grafana - remove conflicting packages
  package:
    name: grafana-data
    state: absent
  register: _old_grafana_pkgs

- name: grafana - add repository
  yum_repository:
    name: grafana
    description: grafana
    baseurl: "{{ grafana_repo }}"
    gpgcheck: yes
    gpgkey: "{{ grafana_repo_key }}"

- name: grafana - install packages
  package:
    name: "{{ grafana_package }}"
    state: "{{ (grafana_version == 'latest') | ternary('latest', 'present') }}"
  register: _install_packages
  until: _install_packages is succeeded
  retries: 5
  delay: 2

- name: grafana - enable service
  systemd:
    name: grafana-server
    state: stopped
    enabled: yes
    daemon_reload: yes

- name : grafana - global configuration
  ini_file:
    path: "{{ grafana_config }}"
    section: "{{item.section}}"
    option: "{{item.option}}"
    value: "{{item.value}}"
  with_items:
    - { section: server, option: http_addr, value: "127.0.0.1" }
    - { section: server, option: root_url, value: "%(protocol)s://%(domain)s/grafana/" }
    - { section: users, option: allow_sign_up, value: "false" }
    - { section: users, option: allow_org_create, value: "false" }
    - { section: users, option: default_theme, value: '"light"' }
    - { section: auth, option: disable_login_form, value: "true" }
    - { section: auth, option: disable_signout_menu, value: "true" }
    - { section: auth.proxy, option: enabled, value: "true" }
    - { section: auth.proxy, option: whitelist, value: "" }
    - { section: auth.anonymous, option: enabled, value: "true" }
    - { section: auth.anonymous, option: org_role, value: "Viewer" }
    - { section: security, option: allow_embedding, value: "true" }

- name: grafana - apache configuration
  template:
    src: grafana/grafana.conf.j2
    dest: "/etc/httpd/conf.d/grafana.conf"