---
- name: histou - checking ressource access
  become: false
  uri:
    url: "{{ histou_git }}"
  register: histou_http_response
  ignore_errors: true

- name: histou - clone project
  become: false
  local_action:
    module: git
    repo: "{{ histou_git }}"
    dest: "{{ histou_git_dir }}"
    update: yes
    force: yes
    accept_hostkey: yes
  run_once: yes
  when: histou_http_response.status == 200

- name: histou - create directory
  file:
    path: "{{ histou_dir }}"
    state: directory

- name: histou - create git directory
  file:
    path: "{{ histou_git_dir }}"
    state: directory

- name: histou - Using local project
  unarchive:
    extra_opts: ['--strip-components=1', '--show-stored-names']
    src: "{{ histou_tgz }}"
    dest: "{{ histou_dir }}"
  when: histou_http_response.status != 200

- name: histou - copy files
  synchronize:
    src: "{{ histou_git_dir }}/"
    dest: "{{ histou_dir }}/"
    owner: false
    group: false
  when: histou_http_response.status == 200

- name: histou - copy configuration file
  copy:
    src: "{{ histou_git_dir }}/histou.ini.example"
    dest: "{{ histou_dir }}/histou.ini"
  when: histou_http_response.status == 200


- name: histou - copy js file
  copy:
    src: "{{ histou_git_dir }}/histou.js"
    dest: "{{ grafana_dir }}/histou.js"
  when: histou_http_response.status == 200


- name: histou - create thruk templates directory
  file:
    path: "{{histou_thruk_template}}"
    state: directory

- name: histou - copy httpd configuration & thruk template
  template:
    src:  "histou/{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - { src: "histou.conf.j2", dest: "/etc/httpd/conf.d/histou.conf" }
    - { src: "_histou_graph.tt.j2", dest: "{{histou_thruk_template}}/_histou_graph.tt" }
  notify: reload httpd

- name: histou - configure influxdb url
  ini_file:
    path: "{{ histou_dir }}/histou.ini"
    section: "influxdb"
    option: "url"
    value: '"{{influxdb_url}}/query?db=nagflux"'
