---
- name: influxdb - add repository
  yum_repository:
    name: influxdb
    description: influxdb
    baseurl: "{{ influxdb_repo }}"
    gpgcheck: yes
    gpgkey: "{{ influxdb_repo_key }}"

- name: influxdb - import rpm key
  rpm_key:
    key: "{{ influxdb_repo_key }}"
    state: present

- name: influxdb - install packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
  - "{{ influxdb_packages }}"
  retries: 5
  delay: 2

- name: influxdb - modify configuration
  ini_file:
    path: "{{ influxdb_config }}"
    section: "{{item.section}}"
    option: "  {{item.option}}"
    value: "{{item.value}}"
  with_items:
    - { section: http, option: bind-address, value: '"127.0.0.1:8086"' }
    - { section: http, option: log-enabled, value: "false" }
    - { section: logging, option: level, value: '"error"' }

- name: influxdb - ensure backup folder exists
  file:
    path: "{{ influxdb_backup_dir }}"
    state: directory
    owner: root
    group: root

- name: influxdb - copy cron backup
  template:
    src: "influxdb/influxdb.cron.j2"
    dest: "/etc/cron.d/influxdb"
    owner: root
    group: root
    mode: 0644

- name: influxdb - enable service
  systemd:
    name: influxdb
    state: stopped
    enabled: yes
    daemon_reload: yes
