---
# task install

- name: disable selinux
  selinux:
    state: disabled

- name: install the 'eyesofnetwork-release' package
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - epel-release
    - https://download.eyesofnetwork.com/repos/{{version}}/base/eyesofnetwork-release-{{version}}-{{release}}.noarch.rpm
    - https://labs.consol.de/repo/stable/rhel7/i386/labs-consol-stable.rhel7.noarch.rpm
    - https://rpm.ocsinventory-ng.org/ocsinventory-release-latest.el7.ocs.noarch.rpm

- name: install the 'EyesOfNetwork Monitoring' package group
  yum:
    name: "@^EyesOfNetwork Monitoring"
    state: latest
    enablerepo: eon-base
    update_cache: yes
    exclude: php-mysql

- name: start eyesofnetwork initialization
  service:
    name: eonconf
    state: started
