---
# task install

- name: disable selinux
  selinux:
    state: disabled

- name: install all repos
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - epel-release
    - https://download.eyesofnetwork.com/repos/{{eon_version}}/base/eyesofnetwork-release-{{eon_version}}-{{eon_release}}.noarch.rpm
    - https://labs.consol.de/repo/stable/rhel7/i386/labs-consol-stable.rhel7.noarch.rpm
    - https://rpm.ocsinventory-ng.org/ocsinventory-release-latest.el7.ocs.noarch.rpm

- name: install the latest 'eyesofnetwork-release' package
  yum:
    name: "eyesofnetwork-release"
    state: latest
    update_cache: yes

- name: install the 'EyesOfNetwork Monitoring' package group
  yum:
    name: "@^EyesOfNetwork Monitoring"
    state: latest
    enablerepo: eon-base
    update_cache: yes
    exclude: php-mysql

- name: check if eon repo exists
  stat: path=/srv/eyesofnetworkrepo
  register: check_path

- name: start eyesofnetwork initialization
  service:
    name: eonconf
    state: started
  when: check_path.stat.exists == false

- name: wait until eyesofnetwork installed
  wait_for:
    path: /srv/eyesofnetworkrepo/extras
    state: present
    msg: "EyesOfNetwork is not installed !"
