---
# task mod_gearman

- name: disable selinux
  selinux:
    state: disabled
  when: "'mod_gearman_worker' in group_names"

- name: install the 'mod_gearman_worker' packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - epel-release
    - https://download.eyesofnetwork.com/repos/{{version}}/base/eyesofnetwork-release-{{version}}-{{release}}.noarch.rpm
    - https://labs.consol.de/repo/stable/rhel7/i386/labs-consol-stable.rhel7.noarch.rpm
    - nagios-plugins-all
    - nagios-plugins-eon
    - perl-Nagios-Plugin
    - perl-Net-SNMP
  when: "'mod_gearman_worker' in group_names"

- name: install 'mod_gearman' packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - gearmand
    - gearmand-server
    - mod_gearman

- name: disable gearmand-server on worker
  service:
    name: gearmand
    enabled: no
    state: stopped
  when: "'mod_gearman_worker' in group_names"

- name: copy secret file to the different node
  template:
    src: mod_gearman/secret.file.j2
    dest: "{{ mod_gearman_key_path }}"
    owner: root
    group: root
    mode: 0644

- name: generate template server to server node
  template:
    src: mod_gearman/module.conf.j2
    dest: /etc/mod_gearman/module.conf
    owner: root
    group: root
    mode: 0644
  when: "'mod_gearman_server' in group_names"

- name: generate template worker to worker node
  template:
    src: mod_gearman/worker.conf.j2
    dest: /etc/mod_gearman/worker.conf
    owner: root
    group: root
    mode: 0644
#  when: "'mod_gearman_worker' in group_names"

- name: enable mod-gearman-worker
  service:
    name: mod-gearman-worker
    enabled: yes
    state: restarted

