---
- name: nagflux - install dependencies
  package:
    name: "{{ item }}"
    state: latest
  with_items:
  - "{{ nagflux_packages }}"

- name: nagflux - create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ nagflux_gopath }}"

- name: nagflux - get go project
  shell: "go get -u {{ nagflux_git }}"
  environment:
    GOPATH: "{{ nagflux_gopath }}"
  changed_when: false

- name: nagflux - build go project
  shell: "go build {{ nagflux_git }}"
  environment:
    GOPATH: "{{ nagflux_gopath }}"
  changed_when: false

- name: nagflux - copy files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    remote_src: yes
  with_items:
    - { src: "{{ nagflux_gopath }}/src/github.com/griesbacher/nagflux/nagflux.service", dest: "/usr/lib/systemd/system/nagflux.service", mode: 644 }

- name: nagflux - configure nagflux service
  ini_file:
    path: "/usr/lib/systemd/system/nagflux.service"
    section: "Service"
    option: "ExecStart"
    value: "{{ nagflux_path }}/nagflux -configPath {{ nagflux_path }}/config.gcfg"

- name: nagflux - enable service
  systemd:
    name: nagflux.service
    state: stopped
    enabled: yes
    daemon_reload: yes

- name: nagflux - disable npcd
  systemd:
    name: npcd
    state: stopped
    enabled: no