---
# Some thruk configuration to make it work with EyesOfNetwork

- name: thruk - ensure cookie auth vhost file is empty
  copy:
    content: ""
    dest: /etc/httpd/conf.d/thruk_cookie_auth_vhost.conf
    force: yes
    group: root
    owner: root
    mode: 0644
  notify: reload httpd

- name: thruk - be sure API is available in httpd
  lineinfile:
    path: /etc/httpd/conf.d/thruk.conf
    regexp: "^\\s+AliasMatch\\s+\\^\\/thruk\\/\\(\\.\\*\\\\.cgi\\|\\.\\*\\\\.html\\)\\s+\\/usr\\/share\\/thruk\\/fcgid_env\\.sh\\/thruk\\/\\$1"
    line: "  AliasMatch ^/thruk/(.*\\.cgi|.*\\.html|r/.*)  /usr/share/thruk/fcgid_env.sh/thruk/$1"
    backrefs: yes
  notify: reload httpd

- name: thruk - set API available from localhost
  lineinfile:
    path: /etc/httpd/conf.d/thruk.conf
    line: "        Require ip 127.0.0.1"
    insertafter: "^        Require valid-user"
  notify: reload httpd

- name: thruk - set admin as default user
  lineinfile:
    path: /etc/thruk/cgi.cfg
    regexp: "^default_user_name=$"
    line: "default_user_name=admin"
    backrefs: yes
  notify: reload httpd
