---
# handlers file for ansible-role-eyesofnetwork

- name: export nagios
  become: true
  uri:
    url: "{{eon_api_url}}/exportConfiguration?username={{eon_api_user}}&apiKey={{eon_api_token}}"
    method: POST
    headers:
      Content-Type: "application/json"
    body: '{ "jobName": {{eon_api_job_name}} }'
    body_format: json
    return_content: yes
    validate_certs: no
  ignore_errors: True
  changed_when: True

- name: restart grafana
  become: true
  service:
    name: grafana-server
    state: restarted

- name: reload httpd
  become: true
  service:
    name: httpd
    state: reloaded

- name: restart httpd
  become: true
  service:
    name: httpd
    state: restarted

- name: restart influxdb
  become: true
  service:
    name: influxdb
    state: restarted

- name: restart nagflux
  become: true
  service:
    name: nagflux
    state: restarted

- name: restart mariadb
  become: true
  service:
    name: mariadb
    state: restarted

- name: restart snmptrapd
  become: true
  service:
    name: snmptrapd
    state: restarted

- name: reload systemd daemon
  systemd:
    daemon_reload: yes