---
# handlers file for ansible-role-eyesofnetwork

- name: restart grafana
  become: true
  service:
    name: grafana-server
    state: restarted

- name: reload httpd
  become: true
  service:
    name: httpd
    state: reloaded

- name: restart influxdb
  become: true
  service:
    name: influxdb
    state: restarted

- name: restart nagflux
  become: true
  service:
    name: nagflux
    state: restarted